# Generated by Django 3.2.5 on 2021-07-23 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domcrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='type name')),
            ],
            options={
                'verbose_name': 'ApplicationStatus',
                'db_table': 'ApplicationStatus',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 23, 16, 52, 12, 775779)),
        ),
        migrations.CreateModel(
            name='ApplicationWStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('application', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='domcrm.application')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='domcrm.applicationstatus')),
            ],
            options={
                'db_table': 'applications_with_status',
                'unique_together': {('application', 'status')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='staus',
            field=models.ManyToManyField(through='domcrm.ApplicationWStatus', to='domcrm.ApplicationStatus'),
        ),
    ]
