# Generated by Django 3.2.5 on 2021-07-23 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domcrm', '0004_auto_20210723_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
