# Generated by Django 3.2.5 on 2021-07-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domcrm', '0005_alter_application_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationWStatus',
        ),
    ]
