# Generated by Django 3.2.5 on 2021-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domcrm', '0006_delete_applicationwstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='short_description',
            field=models.TextField(default='', max_length=400, verbose_name='short description'),
        ),
    ]
